### ISSUE TITLE
UNETR for 2D Segmentation

### ISSUE THREAD

**Issue by kabbas570** [Project-MONAI/research-contributions#127]
Hi, thanks for the contributions to the scientific community.
Can we use UNETR for 2D images? I am trying to put the last channel = 1, but I think all the conv filters at the backend are 3D.

Do you have any implementation for 2D ?

Thanks

**Comment by wyli** [comment]
yes, you can set `spatial_dims=2`..

**Comment by kabbas570** [comment]
Thanks, its also has issue for self.patch_size = (16, 16, 16).

**Comment by wyli** [comment]
I see, you can use the version in monai: https://github.com/Project-MONAI/MONAI/blob/1.0.0/monai/networks/nets/unetr.py

**Comment by kabbas570** [comment]
Thanks, @wyli , yes, it's working for the 2D case.
