### ISSUE TITLE
Training Error with SwinUnetr for Brain Tumor Segmentation

### ISSUE THREAD

**Issue by Sharifmhamza** [Project-MONAI/research-contributions#134]
Hello Monai Team,

I am using SwinUNETR for the brain tumor segmentation task. I have used your provided script but got this error as the input channel of MRI images is 4 but got 240. Can you tell provide suggestions for resolving this issue? Waiting for your response. 

Thank you

<img width="959" alt="Screen Shot 2022-10-13 at 6 21 50 AM" src="https://user-images.githubusercontent.com/32780776/195484056-20613ef8-a90a-4687-92ff-3d05bf0f6078.png">

**Comment by tangy5** [comment]
Hi @Sharifmhamza , thanks for the question. The BRATS data used for this SwinUNETR release is BRATS21 challenge data. I guess there might be a pre-processing difference regarding different version of BRATS data. For example, if the brats data are from MSD (Task01, brats 2016), you might need to use EnsureChannelFirstd to force the number of channels (4) as the first dimension before converting to Tensor. You could have a try if this is the problem. 
Thanks

**Comment by Sharifmhamza** [comment]
Thank you @tangy5. This worked for me.
