### ISSUE TITLE
BRATS DATASET has three classes, TC, WT, and ET. Performance always comes zero for third class during validation

### ISSUE THREAD

**Issue by Sharifmhamza** [Project-MONAI/research-contributions#138]

**Comment by Sharifmhamza** [comment]
Hello MONAI TEAM,

I am facing an issue with BRATS challenge dataset that is used in UNETR. While training with SWINUNETR, I always get a zero dice score for the ET class. During inference, I got this error shown in the attached screenshot. Can you suggest me to resolve the issue? Waiting for your response. Thank you.
<img width="985" alt="Screen Shot 2022-10-18 at 1 41 51 AM" src="https://user-images.githubusercontent.com/32780776/196289372-b8ba873d-0d3f-4ddb-a363-01997a766023.png">

**Comment by tangy5** [comment]
Hi @Sharifmhamza , the BRATS data used in UNETR should be the MSD Task01, which is from BRATS16. The SwinUNETR used BRATS21 data for experiments. The original data formats, construction of labels are different. The loss function are configured slightly different. Sigmoid is used in the SwinUNETR, and output channel is 3, no background. The difference might be the reason causing errors.

**Comment by Mentholatum** [comment]
> Hi @Sharifmhamza , the BRATS data used in UNETR should be the MSD Task01, which is from BRATS16. The SwinUNETR used BRATS21 data for experiments. The original data formats, construction of labels are different. The loss function are configured slightly different. Sigmoid is used in the SwinUNETR, and output channel is 3, no background. The difference might be the reason causing errors.

Hello Contributor, I am using Swin UNETR on the BraTS21 dataset with an output channel of 3 and using sigmoid (as per the files in the project), but in the validation results, the ET (Enhancing Tumor) is still close to 0. Do you know what might be causing this issue?

**Comment by Dasha484** [comment]
Hello, I encountered this issue during network training as well, where the third class (ET) consistently has a Dice score of 0. Did you manage to resolve it? Do you have any suggestions?

**Comment by Luffy03** [comment]
Hi, we reproduce the results at https://github.com/Luffy03/Large-Scale-Medical. You can find our implementation at https://github.com/Luffy03/Large-Scale-Medical/tree/main/Downstream/monai/BRATS21.
