### ISSUE TITLE
Output Predictions are not saved properly. Get squeezed

### ISSUE THREAD

**Issue by Sharifmhamza** [Project-MONAI/research-contributions#140]
Hi Monai Team, 

I am saving output prediction using the code provided at this link: [https://github.com/Project-MONAI/research-contributions/blob/main/UNETR/BTCV/test.py](url) but the predictions get squeezed. I am attaching the screenshot of the 
label and output predictions, can you help me to resolve the issue?
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/32780776/197204616-62300d82-924d-4f48-9982-29dd0b06a34c.png)

**Comment by tangy5** [comment]
Hi @Sharifmhamza , the test.py code is not saving the output prediction, if you are going to save the validation/test prediction for visualization, there might be needed to add **Invertd** (https://docs.monai.io/en/stable/transforms.html?highlight=invertd#monai.transforms.Invertd) transform for recovering all meta information, headers, to it's original image space. 
Thanks.
