### ISSUE TITLE
Running UNETR independant on MONAI

### ISSUE THREAD

**Issue by salman-moh** [Project-MONAI/research-contributions#142]
Is it possible to run UNETR without monai library? how would this be done if any hints can be given that would be helpful!

**Comment by tangy5** [comment]
Hi @salman-moh , UNETR is a part of work of MONAI team, we would not recommend to do so. But for development purpose, you could pull the MONAI library and use/import networks scripts locally, then make changes, training with those changes accordingly. 
https://github.com/Project-MONAI/MONAI/tree/dev/monai/networks
Copy and import "from networks import UNETR"
