### ISSUE TITLE
I have bug

### ISSUE THREAD

**Issue by Ban1-cmyk** [Project-MONAI/research-contributions#147]
![image](https://user-images.githubusercontent.com/82276505/203925269-c365e4ab-e9a4-4ef6-b238-80ba188a05b2.png)
I don't know what it keeps reminding me of “__init__() got an unexpected keyword argument 'n_classes' ”.

**Comment by mingxin-zheng** [comment]
@Ban1-cmyk can you provide some more info, for example, which script in the repo causes this problem? Thanks!

**Comment by Ban1-cmyk** [comment]
![image](https://user-images.githubusercontent.com/82276505/203937527-91433b43-be93-4aae-9e1d-b5eeb2b0c8d7.png)
![image](https://user-images.githubusercontent.com/82276505/203937999-8ebdf738-68c8-4e44-b9e2-2f35999e374e.png)

**Comment by Ban1-cmyk** [comment]
> @Ban1-cmyk can you provide some more info, for example, which script in the repo causes this problem? Thanks!
![image](https://user-images.githubusercontent.com/82276505/203938257-c692bdb1-1612-4e1a-b2cd-c76a30788a95.png)
![image](https://user-images.githubusercontent.com/82276505/203938289-723e481c-89cb-40eb-8980-f4071ad40506.png)
Thank youuuuuuuu!!!!!!!!!
