### ISSUE TITLE
After the training, the accuracy is 0. “Training Finished !, Best Accuracy: 0.0”  What is the situation   

### ISSUE THREAD

**Issue by hnjzbss** [Project-MONAI/research-contributions#17]
**Describe the bug**

**To Reproduce**
2. Install '....'
3. Run commands '....'

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS
 - Python version
 - MONAI version [e.g. git commit hash]
 - CUDA/cuDNN version
 - GPU models and configuration

**Additional context**
@

**Comment by ahatamiz** [comment]
Hi @hnjzbss 

I was able to reproduce this issue. 

Based on this, I have submitted a new pull request (#18 ) that addresses this issue. Please re-try once it's merged. 

Thanks
