### ISSUE TITLE
In the "pretrain" codes, "Spacingd" is not used in transforms. So the "space_x", "space_y" and "space_z" in "main.py" does not work.

### ISSUE THREAD

**Issue by oyxhust** [Project-MONAI/research-contributions#192]
In the "pretrain" codes, "Spacingd" is not used in transforms. So the "space_x", "space_y" and "space_z" in "main.py" does not work.

**Comment by tangy5** [comment]
Thanks for figuring out. Yes, these pixdim params are not used in this released code. Image's original resolution is used for training. Originally, we tried different isotropic resolution for pretraining. ..

We can remove this in the future.

**Comment by oyxhust** [comment]
Thanks for the kind reply.

**Comment by oyxhust** [comment]
Thanks for the kind reply.
