### ISSUE TITLE
SWIN UNETR forward_part1 norm layer erroring out

### ISSUE THREAD

**Issue by alpergel** [Project-MONAI/research-contributions#194]
Hello, Im feeding the network data with size of [1,128,128,128] but I keep getting the following error: "RuntimeError: Given normalized_shape=[48], expected input with shape [*, 48], but got input of size[48, 64, 64, 64]". Is there a model setting that I am not setting correctly? 

Thank you so much in advance!

**Environment (please complete the following information):**
 - Google Colab
 - GPU: NVIDIA Tesla T4

**Comment by peterhessey** [comment]
Linking [this discussion](https://github.com/Project-MONAI/tutorials/discussions/1235) here as I believe they're related. It seems that the pre-trained weights being used for SwinUNet are not being set up correctly for all datasets.

**Comment by tangy5** [comment]
Which codebase are you using, the BRATS segmentation or the BTCV?  The pretrained weights can be different on different tasks, BRATS task used 128x128x128 as input, BTCV CT segmentation used 96x96x96. The size might matters here.

**Comment by peterhessey** [comment]
@tangy5 I'm not sure which codebases you are referring to. I am just trying to using the Auto3dSeg AutoRunner with the following command:

```shell
python -m monai.apps.auto3dseg AutoRunner run --input='./task.yaml'
```

In the generated `train.py` for each of the SwinUnet folds, it appears the the weights are being downloaded from the following URL:

> "https://github.com/Project-MONAI/MONAI-extra-test-data/releases/download/0.8.1/swin_unetr.base_5000ep_f48_lr2e-4_pretrained.pt"

Does this answer your question?

**Comment by mingxin-zheng** [comment]
The issue seems resolved in another thread. I'm closing this one.

**Comment by peterhessey** [comment]
@mingxin-zheng can you please link the thread where this was resolved?
