### ISSUE TITLE
No weight file after training

### ISSUE THREAD

**Issue by pcl1121** [Project-MONAI/research-contributions#199]
when I finished the training，the ./runs/test file only have events.out.tfevents , there is no weight file in it,how can I fix it?

**Comment by pcl1121** [comment]
No validation steps in my training, only train, I finally solved this problem
change
parser.add_argument("--save_checkpoint", action="store_true", help="save checkpoint during training")
to
parser.add_argument("--save_checkpoint", default=True, help="save checkpoint during training")

**Comment by tangy5** [comment]
Great news, thanks, I will close this issue, feel free to drop questions.
