### ISSUE TITLE
data split of UNETR

### ISSUE THREAD

**Issue by 282857341** [Project-MONAI/research-contributions#21]
Thanks for your great work! Can you provide me with the data split of the Brain Tumour, spleen and BTVC? Thanks you a lot.

**Comment by ahatamiz** [comment]
Hi @282857341 

Thanks for your interest in our work. We will release brain and spleen splits upon release of their codes. 

For BTCV, the numbers reported in the [paper](https://arxiv.org/pdf/2103.10504.pdf) are directly from the test leaderboard. We also provided a sample split for training and evaluating our model [here](https://drive.google.com/file/d/1t4fIQQkONv7ArTSZe4Nucwkk1KfdUDvW/view). 

Thanks
