### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by xychen2022** [Project-MONAI/research-contributions#22]
I got CUDA out of memory during inference. How to solve this problem? (I have a total of 60 validation images and the code stopped after processing the 52nd image). Thanks

sliding_window_inference
    count_map = torch.zeros(output_shape, dtype=torch.float32, device=device)
RuntimeError: CUDA out of memory. Tried to allocate 1.57 GiB (GPU 0; 11.91 GiB total capacity; 9.01 GiB already allocated; 826.94 MiB free; 10.27 GiB reserved in total by PyTorch)

Val 99/5000 0/60 acc 0.69666123 time 71.59s
Val 99/5000 1/60 acc 0.7665866 time 19.51s
Val 99/5000 2/60 acc 0.74568444 time 19.14s
Val 99/5000 3/60 acc 0.7421014 time 41.73s
Val 99/5000 4/60 acc 0.74470216 time 14.27s
Val 99/5000 5/60 acc 0.6023531 time 48.11s
Val 99/5000 6/60 acc 0.63559777 time 47.31s
Val 99/5000 7/60 acc 0.7078452 time 28.05s
Val 99/5000 8/60 acc 0.7461889 time 28.38s
Val 99/5000 9/60 acc 0.72240114 time 25.68s
Val 99/5000 10/60 acc 0.7349031 time 19.32s
Val 99/5000 11/60 acc 0.5812509 time 51.07s
Val 99/5000 12/60 acc 0.56357753 time 51.10s
Val 99/5000 13/60 acc 0.7025258 time 39.52s
Val 99/5000 14/60 acc 0.6934635 time 34.07s
Val 99/5000 15/60 acc 0.71059304 time 43.36s
Val 99/5000 16/60 acc 0.6659618 time 47.43s
Val 99/5000 17/60 acc 0.6793316 time 61.28s
Val 99/5000 18/60 acc 0.51980585 time 21.26s
Val 99/5000 19/60 acc 0.7111399 time 47.38s
Val 99/5000 20/60 acc 0.68195075 time 43.40s
Val 99/5000 21/60 acc 0.7277525 time 61.09s
Val 99/5000 22/60 acc 0.5373005 time 18.68s
Val 99/5000 23/60 acc 0.63938075 time 23.21s
Val 99/5000 24/60 acc 0.5794002 time 55.23s
Val 99/5000 25/60 acc 0.59343034 time 20.44s
Val 99/5000 26/60 acc 0.5908409 time 27.87s
Val 99/5000 27/60 acc 0.6639712 time 23.38s
Val 99/5000 28/60 acc 0.6337707 time 10.55s
Val 99/5000 29/60 acc 0.636496 time 23.24s
Val 99/5000 30/60 acc 0.62790823 time 9.39s
Val 99/5000 31/60 acc 0.59033436 time 21.28s
Val 99/5000 32/60 acc 0.6143217 time 4.17s
Val 99/5000 33/60 acc 0.6142419 time 27.90s
Val 99/5000 34/60 acc 0.6083099 time 60.02s
Val 99/5000 35/60 acc 0.6023102 time 46.00s
Val 99/5000 36/60 acc 0.5558359 time 22.66s
Val 99/5000 37/60 acc 0.59874105 time 23.64s
Val 99/5000 38/60 acc 0.6033232 time 12.78s
Val 99/5000 39/60 acc 0.6222449 time 4.19s
Val 99/5000 40/60 acc 0.61932653 time 46.00s
Val 99/5000 41/60 acc 0.57913965 time 23.35s
Val 99/5000 42/60 acc 0.66750497 time 25.70s
Val 99/5000 43/60 acc 0.6848543 time 26.12s
Val 99/5000 44/60 acc 0.6810599 time 25.68s
Val 99/5000 45/60 acc 0.6120205 time 39.74s
Val 99/5000 46/60 acc 0.6246956 time 39.86s
Val 99/5000 47/60 acc 0.58194286 time 39.77s
Val 99/5000 48/60 acc 0.5662599 time 47.26s
Val 99/5000 49/60 acc 0.56202275 time 27.64s
Val 99/5000 50/60 acc 0.70149297 time 54.35s
Val 99/5000 51/60 acc 0.7281418 time 30.59s
Val 99/5000 52/60 acc 0.6984218 time 68.52s

**Comment by ahatamiz** [comment]
Hi @xychen2022 

One straight solution is to decrease `infer_overlap`. It seems that case `52` constitutes a very large volume, hence sliding window with high overlap results in OOM. 

I hope this helps. 

Thanks,
