### ISSUE TITLE
Getting Error RuntimeError: applying transform <monai.transforms.compose.Compose object at 0x7f1390f7d880> while trying to replicate results

### ISSUE THREAD

**Issue by SaiSandeepRaguru** [Project-MONAI/research-contributions#220]
![image](https://user-images.githubusercontent.com/62465620/232544631-73a21b1e-504c-4695-b0d4-3b4a0714d0d0.png)
![image](https://user-images.githubusercontent.com/62465620/232544681-e468b7d0-28ef-40c5-b98f-44c9b5409eae.png)
Please help me in resolving this issue

**Comment by SiruLiu645** [comment]
I have this problem,too.Did you solve it?

**Comment by SaiSandeepRaguru** [comment]
it was because, i didnt download exact dataset, i guess u are also doing same thing
