### ISSUE TITLE
num_steps_per_image>1  test_integration_autorunner

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/research-contributions#227]
> there's still an error after the above ones being fixed
> 
> ```
> ======================================================================
> ERROR: test_autorunner_ensemble (__main__.TestAutoRunner)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/Documents/MONAI/tests/test_integration_autorunner.py", line 132, in test_autorunner_ensemble
>     runner.run()
>   File "/home/Documents/MONAI/monai/apps/auto3dseg/auto_runner.py", line 803, in run
>     self._train_algo_in_sequence(history)
>   File "/home/Documents/MONAI/monai/apps/auto3dseg/auto_runner.py", line 659, in _train_algo_in_sequence
>     acc = algo.get_score()
>   File "/home/Documents/MONAI/monai/apps/auto3dseg/bundle_gen.py", line 264, in get_score
>     dict_file = ConfigParser.load_config_file(os.path.join(ckpt_path, "progress.yaml"))
>   File "/home/Documents/MONAI/monai/bundle/config_parser.py", line 402, in load_config_file
>     with open(_filepath) as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpd2llrjiy/work_dir/segresnet_0/model/progress.yaml'
> ```

this is still an issue when `num_steps_per_image>1`, @myron prgoress.yaml was not saved properly. but we are merging this and overriding it to `num_steps_per_image=1` in the test cases because we want to run full integration tests to unblock the release.

_Originally posted by @wyli in https://github.com/Project-MONAI/research-contributions/issues/224#issuecomment-1513181919_

**Comment by myron** [comment]
this PR should fix it https://github.com/Project-MONAI/research-contributions/pull/237
