### ISSUE TITLE
Hi! When the code of Swin UNETR will be release? it is a interesting work : )

### ISSUE THREAD

**Issue by BossZard** [Project-MONAI/research-contributions#25]
Hi! When the code of Swin UNETR will be release? it is a interesting work : )

**Comment by ahatamiz** [comment]
Hi @BossZard 

Thanks for your interest in our work. Given the extensive of this project, we plan on gradual release of the code for each MSD task. Hence, a new update shall be pushed very soon. 

Overall, we plan on officially releasing the entire repositories with the latest release of MONAI. More information regarding this release can be found here:
https://monai.io/

Thanks

**Comment by ljljlj02** [comment]
Good job, I'm looking forward to it.

**Comment by Puzzled-Hui** [comment]
> Hi @BossZard
> 
> Thanks for your interest in our work. Given the extent of this project, we plan on gradual release of the code for each MSD task. Hence, a new update shall be pushed very soon.
> 
> Overall, we plan on officially releasing the entire repositories with the latest release of MONAI. More information regarding this release can be found here: https://monai.io/
> 
> Thanks

Hi, thanks for your great work! May I ask you the schedule of the code releasing timeline?

**Comment by winnerziqi** [comment]
Hi, thanks for your great work! May I ask you the schedule of the code releasing timeline?

**Comment by wyli** [comment]
thanks, addressed by creating https://github.com/Project-MONAI/research-contributions/pull/53
