### ISSUE TITLE
Train on specified GPUs

### ISSUE THREAD

**Issue by pcl1121** [Project-MONAI/research-contributions#293]
Hello, how to train on the specified gpu, if I have 8 Gpus, only 2 and 3 are not used, I only want to train on the number of 2 and 3 gpu, how should I set in the code?

**Comment by wyli** [comment]
I think you can `export CUDA_VISIBLE_DEVICES=2,3` in bash before running the python scripts. (please help report any issues if this doesn't work..)

**Comment by pcl1121** [comment]
> I think you can `export CUDA_VISIBLE_DEVICES=2,3` in bash before running the python scripts. (please help report any issues if this doesn't work..)

It really worked, problem solved. Thanks for your help
