### ISSUE TITLE
I have a question about coplenet implementation. 

### ISSUE THREAD

**Issue by babbu3682** [Project-MONAI/research-contributions#3]
Thank you for sharing your code!
And I have a question about coplenet implementation.

CopleNet is definitely a 2D unet model that uses conv2d. However, the code clearly contains 3d input (nii data), and uses the sliding window function. Does the sliding window function automatically process 3d input even though the model is 2d based model??

p.s. there is no train code. could you share the train code?

**Comment by massimilianoporzio** [comment]
It would be useful having the train code! Please help us in learning

**Comment by Gijz33** [comment]
Hi @babbu3682 and @massimilianoporzio,
I see you both worked with COPLE-NET before, did you got it running in the end?

I have it running at the moment, but training is very slow. Around 13 epochs in 3 days. I was wondering if this is normal behaviour of the network. Do you have similar experience with COPLE-NET?

**Comment by massimilianoporzio** [comment]
I have a little experience on that...several months ago...if I remember
well I managed to run it...but I tried on my GPU and it is a RTX
3090..maybe on your GPU is slower...also the pipeline for preprocess your
images is important..maybe the bottleneck is the dataset processing for
feeding the net...have you tried with cached Datasets?

Il giorno gio 18 nov 2021 alle ore 10:50 Gijz33 ***@***.***>
ha scritto:

**Comment by Gijz33** [comment]
Thank you for your reply @massimilianoporzio.
I'm running my model on a  V100. I'm also using cached datasets.
Other MONAI architectures run perfectly fine using the same model, so I was a bit surprised by these computation times.
