### ISSUE TITLE
normalization into [0, 1] using window width/level of 1500/-650

### ISSUE THREAD

**Issue by aivision2022** [Project-MONAI/research-contributions#305]
**Is your feature request related to a problem? Please describe.**

To segment COVID-19 pneumonia lesions from your own images, make sure that the images have been cropped into the lung region, and the intensity has been normalized into [0, 1] using window width/level of 1500/-650

=> you mentioned the message above. I would like to test some dicom or nifti files with your code. Could you let me know how to do the pre-processing mentioned above with my own dicom or nifti files ?

**Comment by wyli** [comment]
it's possible to achieve the windowing with
```py
monai.transforms.ScaleIntensityRange(
    a_min=-650-(1500/2.), a_max=-650+(1500/2.), b_min=0, b_max=1
)
```

**Comment by aivision2022** [comment]
Additionally, I have some questions. Thank you for your kind reply.

I don't know how to open your result file, case_1_seg.nii.gz

1. I have tried to open it by https://socr.umich.edu/HTML5/BrainViewer. but failed it.

2. I don't understand why the result nifti file is smaller than the original.
   case_1.nii.gz 31.7MB (input) vs. case_1_seg.nii.gz 756K (output)

3. After run run_inference.py, how to get the image files like yours, [img.png](https://github.com/Project-MONAI/research-contributions/blob/main/coplenet-pneumonia-lesion-segmentation/fig/img.png, or https://github.com/Project-MONAI/research-contributions/blob/main/coplenet-pneumonia-lesion-segmentation/fig/seg.png
