### ISSUE TITLE
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

### ISSUE THREAD

**Issue by pluto-the-planet** [Project-MONAI/research-contributions#328]
**Describe the bug**
I'm running UNETR on my local terminal within a virtual environment.
while running my main.py file on the command line, I face this issue

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a virtual environment on the terminal 
3. Install "pip install requirement.txt"
5. Run 'python main.py'

**Screenshots**
<img width="562" alt="image" src="https://github.com/Project-MONAI/research-contributions/assets/86825641/1a4eec0f-f281-4eb7-b937-3d49f4a87865">

**Environment (please complete the following information):**
 - MACOS M1
 - Python 3.8.10
 - The rest of the libraries are according to requirements.txt

**Comment by wyli** [comment]
thanks for reporting, support of M1 is tracked here https://github.com/Project-MONAI/MONAI/issues/6043
