### ISSUE TITLE
Unable to run prostate-mri-lesion-seg on Colab

### ISSUE THREAD

**Issue by fedorov** [Project-MONAI/research-contributions#342]
@jtetrea trying to run this notebook https://github.com/Project-MONAI/research-contributions/blob/main/prostate-mri-lesion-seg/tutorial.ipynb on Google Colab leads to this error:

<img width="1194" alt="image" src="https://github.com/Project-MONAI/research-contributions/assets/313942/09fdc3b1-00fb-440d-bf17-891d56057317">

If this notebook is not expected to run on Colab, it would be nice to indicate the prerequisites/limitations in the opening paragraph.

But also it would be nice to make it work on Colab, since IMHO it is the easiest way to try things out quickly.

**Comment by jtetrea** [comment]
Thanks @fedorov for giving this a try. The notebook was not intended to be executed standalone on Colab. It references application code and so the full repository should be present and available.

Executing on Colab, just with the notebook, would be possible if some cells were added to write the application files locally throughout. This would be similar to other MONAI Deploy examples such as the [segmentation app tutorial here](https://github.com/Project-MONAI/monai-deploy-app-sdk/blob/main/notebooks/tutorials/03_segmentation_app.ipynb). This would be possible and may be added in the future but for now the tutorial.ipynb should be used with full repository available locally.

**Comment by jtetrea** [comment]
Thanks @fedorov. Yes, MONAI MAPs are containerized solutions for deployment of MONAI models. By the way, there are also some additional scripts in the repository, such as the `scripts/local-test.sh` script that executes the application code outside of the container (the other script executes within a MAP, but outside a Jupyter environment). Feel free to try that script if you have interest on Colab as it may circumvent the Docker issue.

**Comment by fedorov** [comment]
@jtetrea I do not have time to do this deep of an investigation. I still think having a notebook that works out of the box with Colab would significantly improve visibility and accessibility of this model. But it's not my project, and I can't make the time to work on fixing it. If you don't have interest/time either, please feel free to close this issue!

**Comment by jtetrea** [comment]
No problem. I agree that having a mechanism to work directly on Colab may improve accessibility for some users. We will consider this as we plan to create extensions and updates to this repository in the near future. Thanks!
