### ISSUE TITLE
Unable to run the prostate-mri-lesion-seg tutorial notebook using jupyter 

### ISSUE THREAD

**Issue by deepakri201** [Project-MONAI/research-contributions#343]
Hi, 

**Describe the bug**

I am working with @fedorov, and I'm trying to run the [tutorial.ipynb](https://github.com/Project-MONAI/research-contributions/blob/main/prostate-mri-lesion-seg/tutorial.ipynb) using jupyter. Unfortunately, I get the following error when using `!monai-deploy package`: 

![image](https://github.com/Project-MONAI/research-contributions/assets/59979551/2474d100-316b-432f-8ac1-5a250ac29506)

**To Reproduce**

1. I have followed the instructions and have a `prostate_mri_lesion_seg` folder with the following files: 
   - models downloaded from [Google Drive](https://drive.google.com/drive/folders/1wO4h5AON0MA3dxwnzl9cJlxjPxsfXcCF) in `/monai_deploy_prostate/prostate_mri_lesion_seg_app/models`
   - .py files for the app downloaded from [GitHub](https://github.com/Project-MONAI/research-contributions/tree/main/prostate-mri-lesion-seg/prostate_mri_lesion_seg_app) in `/monai_deploy_prostate/prostate_mri_lesion_seg_app`
   - ProstateX data downloaded from [Google Drive](https://drive.google.com/drive/folders/1wO4h5AON0MA3dxwnzl9cJlxjPxsfXcCF) in `/monai_deploy_prostate/test_data/ProstateX-0004`
2. I have created an environment and run `pip install monai-deploy-app-sdk==0.5.1` as written the instructions, as well as installed additional dependencies such as `pydicom` ,`highdicom`, `jupyter`, etc. 
3. When I run the following cell in the `tutorial.ipynb` notebook, I get the error above where the app does not exist. 

**Environment (please complete the following information):**
 - OS = Ubuntu 20.04 
 - Python version = 3.8.10
 - MONAI version [e.g. git commit hash] = 1.3.0
 - CUDA/cuDNN version = CUDA version 12.0 
 - GPU models and configuration = A100X-8C 

Thank you! 

Deepa

**Comment by jtetrea** [comment]
Thanks for giving the code a try @deepakri201! 

The only thing that I can really give feedback based on the error you shared is to make sure that the notebook and the repository are in the right location...the notebook is originally designed to be executed right alongside the application folder, just as it is in the repository. I see that you changed the reference of the folder to an absolute path instead of the relative one...this shouldn't cause an error, but please verify location on your system is referenced properly. Otherwise try keeping as-is and executing alongside application code.

@fedorov I see the issue that you raised in #342 when trying to execute on Colab that is also similar. If you just run the notebook in Colab without cloning the full repository files, it will not be able to build the container.

**Comment by deepakri201** [comment]
Thanks for responding! 

I was able to fix the above error (I had the wrong path name). Now I'm able to run the `!monai-deploy package` successfully, and also run the `load_and_visualize_dicom_image`. 

However now I am running the following command `!monai-deploy run lesion_seg_workflow_app:v1.0 {dcm_dir} output` and get the following error about the organ model not being found: 

![image](https://github.com/Project-MONAI/research-contributions/assets/59979551/df605ae9-1bac-4c66-8fda-40c37e05bb05)

I've downloaded the models from the Google drive folder, and placed them in `prostate_mri_lesion_seg_app/models` as the tutorial says. This is what my folder structure looks like: 

![image](https://github.com/Project-MONAI/research-contributions/assets/59979551/183e6b10-5ee6-44a7-96c1-a148dabe2245)

I've also verified that the `model.ts` file does in fact exist in the `organ` folder. 

Am I supposed to put the models in a different folder? Thanks! 

Deepa

**Comment by deepakri201** [comment]
Hi @jtetrea, 

I checked my version numbers and I'm also using `monai==1.3.0` and `monai-deploy-app-sdk==0.5.1`. 

Interestingly, I re-ran everything (`!monai-deploy package` and` !monai-deploy run`), and now it seems to find the model just fine :) I was able to go through the notebook without any further issues. 

Thank you for your help! 

Deepa

**Comment by jtetrea** [comment]
That is great news! We appreciate your interest in this model. Please reach out if needed as you continue using it. Cheers!
