### ISSUE TITLE
The Implementation of Residual Block in Swin Unetr

### ISSUE THREAD

**Issue by PerPerZXY** [Project-MONAI/research-contributions#43]
Hi!  thank you very much for you great work! 
The Residual Block described in the Swin Unetr paper seems to reduce the channel dimension, but generally the Residual Block in the vanilla ResNet will not change the channel dimension. So I have a question regarding how you implemented the Residual Block in Swin Unetr. Is there a 1^1^1 conv layer added after the general Residual Block? I am a beginner of deep learning and I would appreciate it if you could answer my question.

**Comment by nohsoocheol** [comment]
I'm not the author, but I think `UnetResBlock` in monai is used.
This block consists of
---conv-norm-activation-conv-norm---activation---
 └------------conv---norm------------┘

Check the documentation https://docs.monai.io/en/stable/networks.html#dynamic-unet-block for further details.

**Comment by wyli** [comment]
addressed by https://github.com/Project-MONAI/research-contributions/pull/53
