### ISSUE TITLE
Slow model convergence

### ISSUE THREAD

**Issue by XIANYUNYEHE-DEL** [Project-MONAI/research-contributions#45]
Hello, thanks for your nice work.
I followed your training strategy in UNTER and  trained model in another dataset of  13 organ segmentation. But the model converges very slowly. I using the CE and Dice loss with  Lr=0.0001. After 200 epoch training, my CEloss is low(0.1) and Diceloss is high(0.9). Dice in Validation is only 0.25. Is this normal？Are there problem in the network architecture or strategy. (45train 5val)
thanks for your reply.

**Comment by sadaf92** [comment]
@XIANYUNYEHE-DEL 
I also faced a similar condition, and I think it's because of background ignorence in the test procedure:
`            for i in range(1, 14):
                organ_Dice = dice(val_outputs[0] == i, val_labels[0] == i)
                dice_list_sub.append(organ_Dice)`

If you like to use the same metric as the training path, try to consider the background also.
