### ISSUE TITLE
About Pretrained Swin Encoder Model

### ISSUE THREAD

**Issue by luoyixi924208423** [Project-MONAI/research-contributions#50]
Hi, thank you for your great work.
I notice the paper Self-Supervised Pre-Training of Swin Transformers for 3D Medical Image Analysis. The paper says that you trained Swin Transformer encoder in several Medical Dataset.I wonder you could  release the Pretrained Encoder Model.Thank you.I'm waiting for your reply.

**Comment by Tharunkumar01** [comment]
Thank you for opening the issue, I am too waiting for the same.

**Comment by winnerziqi** [comment]
also too

**Comment by ZongyuLi-umich** [comment]
See this: [https://github.com/HuCaoFighting/Swin-Unet](url)

**Comment by wyli** [comment]
please see https://github.com/Project-MONAI/research-contributions/pull/53
