### ISSUE TITLE
Ask for the code for running Swin UNETR on BraTS dataset

### ISSUE THREAD

**Issue by TanThinNguyen** [Project-MONAI/research-contributions#56]
Hi, thank you for your great work.

In the paper, you said that you train and evaluate the Swin UNETR model on the BraTS 2021. I see in the repo has 2 folders BTCV and BRATS2021 but the BRATS2021 is empty. Would you release code for running Swin UNETR on this dataset?

While waiting for the release, I am trying to modify the BTCV code to run on the BraTS2021. Would you give me some instructions to do this efficiently?

Thank you.
Tan Thin.

**Comment by ahatamiz** [comment]
Hi @TanThinNguyen 

Thanks for your interest and suggestion. Sure, I will release the code for BRATS21 very soon. Please stay tuned. 

Kind Regards

**Comment by TanThinNguyen** [comment]
Thank you for your reply @ahatamiz.
